### ISSUE TITLE
Last collected token does not appear on token door

### ISSUE THREAD

**Issue by paulkim26** [paulkim26/collab-worldtour1#120] opened 2024-08-07 19:09 UTC
## Steps to reproduce

1. Collect all tokens , ending with the one on the camera lens in the central hub.
2. Door can open, but the last token does not appear on door.

This is how the door appears after 20 tokens are collected.
![image](https://github.com/user-attachments/assets/5ccf21d2-eca3-4fa6-9314-92a0c82c5dc4)

## Expected result

All 20 tokens should be visible on token door after they are collected.

**Comment by paulkim26** [comment] 2024-08-07 22:48
@mrogx Would you mind taking this on? I would do this, but it appears you are converting `lua_tokens.lua` script to be a one-liner and obfuscating the variables/functions/strings in a specific way that is not human readable.

**Comment by mrogx** [comment] 2024-08-08 02:18
The issue was that the last (global) picked up token would not become visible on the door, regardless which one it was.

The issue is now fixed.

**Closed by mrogx** 2024-08-08 02:18 UTC
